fix: solve issue where skipped=approved

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,10 +61,38 @@ jobs:
     if: always() 
     runs-on: ubuntu-latest
     steps:
-      - name: Verify all jobs passed
-        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-        run: |
-          echo "Um dos jobs falhou ou foi cancelado."
-          exit 1
-      - name: Success
-        run: echo "Todos os jobs relevantes passaram ou foram skippados com segurança!"
+      - name: Verify job results
+        env:
+          CHANGES_RESULT: ${{ needs.change.result }}
+          BACKEND_CHANGED: ${{ needs.changes.output.backend }}
+          BACKEND_RESULT: ${{ needs.change.backend.result }}
+          FRONTEND_CHANGED: ${{ needs.change.output.frontend }}
+          FRONTEND_RESULT: ${{ needs.change.frontend.result }}
+        shell: bash
+        run: | 
+          set -euo pipefail
+
+          if [[ "$CHANGES_RESULT" != "success"]]; then 
+              echo "::error::changes job finished with $"CHANGES_RESULT"
+              exit 1
+          fi
+
+        case "${BACKEND_CHANGED}:${BACKEND_RESULT}" in
+          true:success|false:skipped) ;;
+          *)
+            echo "::error: unexpected backend state: changed=$BACKEND_CHANGED result=$BACKEND_RESULT"
+            exit 1
+            ;;
+        esac
+        
+        case "${FRONTEND_CHANGED}:${FRONTEND_RESULT}" in
+          true:success|false:skipped) ;;
+          *)
+            echo "::error: unexpected backend state: changed=$FRONTEND_CHANGED result=$FRONTEND_RESULT"
+            exit 1
+            ;;
+        esac
+
+        echo "All jobs have passed."
+
+
